#!/bin/bash

#if [ ${UID} -ne 0 ]
then

echo
echo "You need root acces"
echo
exit 0
fi
## check nuber of processors

c= `nproc
`

if  -[  ${C} eq 1 ]
then

echo "This server is very small"

fi

# Checking memory 

free -m
